service: mime-sniffer-test

provider:
  name: aws
  runtime: ruby2.5

  stage: test
  region: ap-northeast-1

functions:
  normal:
    handler: handler.normal

    events:
      - http:
          path: normal
          method: get

  mimesniffing:
    handler: handler.mimesniffing

    events:
      - http:
          path: mimesniffing
          method: get

  nosniff:
    handler: handler.nosniff

    events:
      - http:
          path: nosniff
          method: get
